owner: armandleopold
repo: statuspage

sites:
  - name: Rancher
    url: https://rancher.armandleopold.fr
  - name: Grafana
    url: https://grafana.armandleopold.fr
  - name: Gitlabmonitor
    url: https://gitlabmonitor.armandleopold.fr
  - name: Blog
    url: https://armandleopold.fr
  - name: Onammu
    url: https://onammu.fr
  - name: Maisondejuncarot
    url: https://maisondejuncarot.fr
  - name: Vault
    url: https://vault.armandleopold.fr

status-website:
  cname: status.armandleopold.fr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Armand LEOPOLD

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
